#+TITLE: NAS-T
#+DESCRIPTION: NAS-Technology
#+AUTHOR: Richard Westhaver <ellis@rwest.io>
#+DATE: 2023-07-28 Fri
#+SETUPFILE: infra/style/clean.theme
#+INFOJS_OPT: view:info toc:nil
* Overview
This is the open-source codebase of The NAS Technology Company
([[https://nas-t.net][NAS-T]]).
- STATUS :: ALPHA
- LICENSE :: [[file:LICENSE][MPL]]
- FORGE :: [[https://lab.rwest.io/comp/nas-t][Heptapod]]
- MIRROR :: [[https://github.com/richardwesthaver/nas-t][Github]]
** Introduction
Welcome to the NAS-T codebase. For more about The NAS Technology
Company refer to the [[file:ABOUT][ABOUT]] file. To contribute, review the [[file:HACKING][HACKING]]
file and [[mailto:ellis@rwest.io][email me]] your patch or idea.
*** Thinking Fast, Going Slow
- [2023-08-01 Tue] :: /a note from the author/ \\
  Greetings stranger. My name is Richard Westhaver and I'm a computer
  programmer living in Connecticut. I started this company as a means
  to provide high-quality NAS solutions to my local community and
  empower others to do the same. There is much work to be done but
  it's quite exciting, and I hope you will be along for the ride :).

  Right now, the ideas are flowing and I'm working through a list of
  experiments, piecing together the perfect solution - the one with
  the most power. Some hardware experiments will follow in the coming
  weeks.

  At this stage, my goals are:
  1. think fast - develop /good/ ideas as quickly as humanly possible
  2. go slow - prioritize detailed implementations

  PS. the website ([[file:infra/web][infra/web]]) is somewhat of an exception - we're just
  throwing that online and coming back to work out the kludges later.
