[workspace]
members = ["client","server"]
resolver = "2"
[profile.release]
lto = true
opt-level = 'z'
strip = true
# [profile.debug]
[profile.dev]
opt-level = 1
overflow-checks = false
debug = true
lto = false
incremental = true