#+OPTIONS: toc:nil num:nil
#+DATE: 2023-08-04 Fri
#+EXPORT_FILE_NAME: client/content
* About
:PROPERTIES:
:EXPORT_FILE_NAME: client/about
:END:
NAS-T is a grassroots Network-Attached Storage (NAS) technology and
service provider based in New London, CT. We are a group of IT and
Data specialists offering a replacement for managed cloud storage
services such as Google Drive, DropBox, iCloud, and OneDrive.

* Products
:PROPERTIES:
:EXPORT_FILE_NAME: client/products
:END:
Our product-line consist of custom-built home servers which run our
open-source and highly configurable NAS software stack. We provide the
software for free without exception, and offer the hardware on our
online store for anyone to purchase and deploy themselves.

* Services
:PROPERTIES:
:EXPORT_FILE_NAME: client/services
:END:
We provide operational support for our products at all levels from
single-user homes to multi-tenant offices at a low monthly cost. Our
fleet of service offerings are designed to support customers who have
little to no technology experience while still providing expert
support to our advanced users who are extending our tools to suit
their needs.

* Motivation
:PROPERTIES:
:EXPORT_FILE_NAME: client/motivation
:END:
The motivation for NAS-T comes from personal frustration with modern
cloud storage services. What started as simple file-sharing has turned
into 'Web File Systems' with a contagious vendor lock-in
effect. Everyone has experienced this at some point - try switching
from Apple to Android, or Windows to Mac, Google Cloud to DropBox. Why
is this so hard? It is because these services are all designed to
protect 'your' data from yourself.

* Solution
:PROPERTIES:
:EXPORT_FILE_NAME: client/solution
:END:
The cloud provider owns your data. You don't even own the rights to
access your data. Access is rented out to you (and others) by the
provider. The solutions we offer remedy that. Our mission, above all,
is to put you /irrefutably/ in total control of your data.
* Mission
:PROPERTIES:
:EXPORT_FILE_NAME: client/mission
:END:
At NAS-T we value your privacy and your right to own your personal
data without exception. We aim to provide the /best/ private cloud
storage software using cutting-edge technology which the large,
entrenched service providers aren't capable of implementing at scale,
and we do it at no cost to our users. We will sell hardware and
services at fair and transparent costs to support our mission and
encourage everyone to take back their data.
