#+TITLE: notes
#+BIBLIOGRAPHY: notes.bib
#+BIND: org-cite-export-processors '((t csl))
* File Systems
** BTRFS
#+begin_quote
BTRFS is a Linux filesystem based on copy-on-write, allowing for
efficient snapshots and clones.

It uses B-trees as its main on-disk data structure. The design goal is
to work well for many use cases and workloads. To this end, much
effort has been directed to maintaining even performance as the
filesystem ages, rather than trying to support a particular narrow
benchmark use-case.

Linux filesystems are installed on smartphones as well as enterprise
servers. This entails challenges on many different fronts.

- Scalability :: The filesystem must scale in many dimensions: disk
  space, memory, and CPUs.

- Data integrity :: Losing data is not an option, and much effort is
  expended to safeguard the content. This includes checksums, metadata
  duplication, and RAID support built into the filesystem.

- Disk diversity :: The system should work well with SSDs and hard
  disks. It is also expected to be able to use an array of different
  sized disks, which poses challenges to the RAID and striping
  mechanisms.
#+end_quote
-- [cite/t/f:@btrfs]
** ZFS
** TMPFS
** EXT4

* Storage Mediums
** HDD
** SDD
** Flash
** NVMe
* Refs
#+print_bibliography:
