#+TITLE: NAS-T
#+SUBTITLE: The NAS Technology Company
#+AUTHOR: Richard Westhaver <ellis@rwest.io>
#+SETUPFILE: infra/style/clean.theme
#+INFOJS_OPT: view:info toc:nil
#+OPTIONS: prop:t toc:nil num:nil title:t
* Overview
:PROPERTIES:
:STATUS: ALPHA
:LICENSE: MPL
:AUTHOR: Richard Westhaver <ellis@rwest.io>
:FORGE: https://lab.rwest.io/comp/nas-t
:MIRROR: https://github.com/richardwesthaver/nas-t
:END:

This is the open-source codebase of the NAS Technology Company (https://nas-t.net).

* About

NAS-T is a grassroots Network-Attached Storage (NAS) technology and service provider
based in New London, CT. We are a group of IT and Data specialists offering a
replacement for managed cloud storage services such as Google Drive, DropBox, iCloud,
and OneDrive.

We build home servers which run our open-source and highly configurable NAS software
stack. We provide the software for free without exception, and offer the hardware at our
online store for anyone to purchase and deploy themselves.

At NAS-T we value your privacy /and/ your right to own your data without exception. We
aim to provide the best /private/ cloud storage service software using cutting-edge
technology which the large, entrenched service providers aren't capable of implementing,
at no cost. We aim to build a community of NAS enthusiasts and experts who can share
their experience and empower their local communities. We will sell hardware and services
at fair and transparent costs to support our mission and encourage everyone to take back
their data.
